var annotated_dup =
[
    [ "AbstractBodyPart", "dd/d50/class_abstract_body_part.html", "dd/d50/class_abstract_body_part" ],
    [ "Body", "d0/dcb/class_body.html", "d0/dcb/class_body" ],
    [ "BodyPart", "d2/d6f/class_body_part.html", "d2/d6f/class_body_part" ],
    [ "CustomSlider", "df/dc1/class_custom_slider.html", "df/dc1/class_custom_slider" ],
    [ "CustomSliderWidget", "d0/dea/class_custom_slider_widget.html", "d0/dea/class_custom_slider_widget" ],
    [ "Dot", "df/ddf/class_dot.html", "df/ddf/class_dot" ],
    [ "DotsPair", "dc/d0f/class_dots_pair.html", "dc/d0f/class_dots_pair" ],
    [ "Heater", "de/d1d/class_heater.html", "de/d1d/class_heater" ],
    [ "HoverPixmapItem", "d9/d15/class_hover_pixmap_item.html", "d9/d15/class_hover_pixmap_item" ],
    [ "ImpulseAdder", "de/d4d/class_impulse_adder.html", "de/d4d/class_impulse_adder" ],
    [ "IntervalDialog", "dd/dd9/class_interval_dialog.html", "dd/dd9/class_interval_dialog" ],
    [ "IntervalDotsPair", "d1/d3e/class_interval_dots_pair.html", "d1/d3e/class_interval_dots_pair" ],
    [ "IntervalSimulation", "dd/dbd/class_interval_simulation.html", "dd/dbd/class_interval_simulation" ],
    [ "IntervalSimulationWidget", "dc/db8/class_interval_simulation_widget.html", "dc/db8/class_interval_simulation_widget" ],
    [ "IntervalWidget", "d8/dc0/class_interval_widget.html", "d8/dc0/class_interval_widget" ],
    [ "LicenceText", "db/d89/class_licence_text.html", "db/d89/class_licence_text" ],
    [ "LicenceUpdate", "d1/d75/class_licence_update.html", null ],
    [ "MainWindow", "d9/dc6/class_main_window.html", "d9/dc6/class_main_window" ],
    [ "MioSuit", "df/d66/class_mio_suit.html", "df/d66/class_mio_suit" ],
    [ "Pointer", "d6/d3b/class_pointer.html", "d6/d3b/class_pointer" ],
    [ "PopBodyPart", "d6/d3b/class_pop_body_part.html", "d6/d3b/class_pop_body_part" ],
    [ "PopDotsPair", "d0/d5f/class_pop_dots_pair.html", "d0/d5f/class_pop_dots_pair" ],
    [ "RecieveDialog", "d7/da6/class_recieve_dialog.html", null ],
    [ "ResizableGraphicsView", "d3/dbe/class_resizable_graphics_view.html", null ],
    [ "SimpleDotsPair", "d9/d91/class_simple_dots_pair.html", "d9/d91/class_simple_dots_pair" ],
    [ "TextRect", "d6/d51/class_text_rect.html", "d6/d51/class_text_rect" ],
    [ "TimeAxis", "de/d63/class_time_axis.html", "de/d63/class_time_axis" ]
];